apiVersion: apps/v1
kind: Deployment
metadata:
  name: gani-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gani
  template:
    metadata:
      labels:
        app: gani
    spec:
      containers:
        - name: gani
          image: gani1990/gani-pipeline:1.0.0-33
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
